package ruh_internship_portal_backend.example.ruh_internship_portal_backend.service;

import ruh_internship_portal_backend.example.ruh_internship_portal_backend.dto.SelectedInternshipDetailsDTO;

public interface SelectedInternshipDetailsService {
    public String getSelectedInternshipDetails(SelectedInternshipDetailsDTO selectedInternshipDetailsDTO);

    String updateSelectedInternshipDetails(SelectedInternshipDetailsDTO selectedInternshipDetailsDTO);
}
